var defaultDesiredItems = [
    "Baby Draik Morphing Potion",
    "Desert Lutari Morphing Potion",
    "Stealthy Krawk Morphing Potion",
    "Plushie Cybunny Morphing Potion",
    "8-bit Power-Up Potion",
    "Maraquan Gelert Morphing Potion",
    "Plushie Aisha Morphing Potion",
    "Stealthy Lutari Morphing Potion",
    "Faerie Draik Morphing Potion",
    "Strange Potion",
    "Baby Chia Morphing Potion",
    "Maraquan Kacheek Morphing Potion",
    "Stealthy Blumaroo Morphing Potion",
    "Wraith Draik Morphing Potion",
    "Maraquan Grarrl Morphing Potion",
    "Plushie Gnorbu Morphing Potion",
    "Halloween Uni Morphing Potion",
    "Green Lutari Morphing Potion",
    "Island Lutari Morphing Potion",
    "Halloween Hissi Morphing Potion",
    "Pink Lenny Morphing Potion",
    "Royal Girl Kyrii Morphing Potion",
    "Maractite Peophin Morphing Potion",
    "Darigan Eyrie Morphing Potion",
    "Wraith Krawk Morphing Potion",
    "Maraquan Acara Morphing Potion",
    "Wraith Korbat Morphing Potion",
    "Darigan Draik Morphing Potion",
    "Plushie Bruce Morphing Potion",
    "Grey JubJub Morphing Potion",
    "Halloween Kyrii Morphing Potion",
    "Plushie Hissi Morphing Potion",
    "Halloween Blumaroo Morphing Potion",
    "Wraith Grundo Morphing Potion",
    "Baby Kacheek Morphing Potion",
    "Faerie Bori Morphing Potion",
    "Blue Draik Morphing Potion",
    "Woodland Uni Morphing Potion",
    "Plushie Poogle Morphing Potion",
    "Island Bruce Morphing Potion",
    "Halloween Aisha Morphing Potion",
    "Pirate Lutari Morphing Potion",
    "Maraquan Ixi Morphing Potion",
    "Pink Lutari Morphing Potion",
    "Faerie Lutari Morphing Potion",
    "Wraith Gelert Morphing Potion",
    "Faerie Krawk Morphing Potion",
    "Desert Aisha Morphing Potion",
    "Faerie Poogle Morphing Potion",
    "Grey Draik Morphing Potion",
    "Transparent Korbat Morphing Potion",
    "Darigan Ixi Morphing Potion",
    "Darigan Wocky Morphing Potion",
    "Plushie Kiko Morphing Potion",
    "Island Quiggle Morphing Potion",
    "Grey Ixi Morphing Potion",
    "Halloween Grundo Morphing Potion",
    "Plushie Skeith Morphing Potion",
    "Faerie Xweetok Morphing Potion",
    "Maraquan Usul Morphing Potion",
    "Maractite Krawk Morphing Potion",
    "Woodland Wocky Morphing Potion",
    "Faerie Lupe Morphing Potion",
    "Faerie Ixi Morphing Potion",
    "Faerie Bruce Morphing Potion",
    "Island Lupe Morphing Potion",
    "Island Ixi Morphing Potion",
    "Halloween Grarrl Morphing Potion",
    "Blue Krawk Morphing Potion",
    "Halloween Ixi Morphing Potion",
    "Faerie Grundo Morphing Potion",
    "Island Gelert Morphing Potion",
    "Faerie Blumaroo Morphing Potion",
    "Halloween Lenny Morphing Potion",
    "Plushie Bori Morphing Potion",
    "Baby Jetsam Morphing Potion",
    "Eventide Tonu Morphing Potion",
    "Plushie Korbat Morphing Potion",
    "Faerie Cybunny Morphing Potion",
    "Wraith Scorchio Morphing Potion",
    "Royal Boy Kyrii Morphing Potion",
    "Rainbow Swirly Potion",
    "Faerie Shoyru Morphing Potion",
    "Baby Lupe Morphing Potion",
    "Stealthy Kyrii Morphing Potion",
    "Darigan Aisha Morphing Potion",
    "Kauvaras Potion",
    "Island Lenny Morphing Potion",
    "Island Bori Morphing Potion",
    "Maractite Draik Morphing Potion",
    "Green Gelert Morphing Potion",
    "Yellow Kacheek Morphing Potion",
    "Water Draik Morphing Potion",
    "Yellow Draik Morphing Potion",
    "Blue Kacheek Morphing Potion",
    "Halloween Bori Morphing Potion",
    "Plushie Usul Morphing Potion",
    "Zombie Eyrie Morphing Potion",
    "Halloween Meerca Morphing Potion",
    "Faerie Peophin Morphing Potion",
    "Woodland Cybunny Morphing Potion",
    "Desert Blumaroo Morphing Potion",
    "Spotted Gelert Morphing Potion",
    "Transparent Elephante Morphing Potion",
    "Baby Aisha Morphing Potion",
    "Faerie Usul Morphing Potion",
    "Maraquan Meerca Morphing Potion",
    "Baby Hissi Morphing Potion",
    "Island Cybunny Morphing Potion",
    "Pastel Xweetok Morphing Potion",
    "Faerie Techo Morphing Potion",
    "Faerie Hissi Morphing Potion",
    "Baby Scorchio Morphing Potion",
    "Maraquan Cybunny Morphing Potion",
    "Island Peophin Morphing Potion",
    "Darigan Blumaroo Morphing Potion",
    "Striped Jetsam Morphing Potion",
    "Baby Kau Morphing Potion",
    "Desert Ixi Morphing Potion",
    "Darigan Buzz Morphing Potion",
    "Halloween Cybunny Morphing Potion",
    "Woodland Bori Morphing Potion",
    "Speckled Cybunny Morphing Potion",
    "Shadow Cybunny Morphing Potion",
    "Red Draik Morphing Potion",
    "Red Cybunny Morphing Potion",
    "Rainbow Lupe Morphing Potion",
    "Rainbow Hissi Morphing Potion",
    "Wraith Pteri Morphing Potion",
    "Maraquan Krawk Morphing Potion",
    "Grey Cybunny Morphing Potion",
    "Maraquan Techo Morphing Potion",
    "Spotted Kau Morphing Potion",
    "Yellow Lupe Morphing Potion",
    "Baby Korbat Morphing Potion",
    "Faerie Lenny Morphing Potion",
    "Spotted Lupe Morphing Potion",
    "Desert Yurble Morphing Potion",
    "Red Jetsam Morphing Potion",
    "Disco Kacheek Morphing Potion",
    "Starry Kacheek Morphing Potion",
    "Starry Cybunny Morphing Potion",
    "Grey Korbat Morphing Potion",
    "Island Hissi Morphing Potion",
    "Faerie Quiggle Morphing Potion",
    "Fire Draik Morphing Potion",
    "Island Kacheek Morphing Potion",
    "Island JubJub Morphing Potion",
    "Yellow Gelert Morphing Potion",
    "Eventide Draik Morphing Potion",
    "Baby Chomby Morphing Potion",
    "Darigan Zafara Morphing Potion",
    "Woodland Draik Morphing Potion",
    "Baby Meerca Morphing Potion",
    "Spotted Kougra Morphing Potion",
    "Spotted Hissi Morphing Potion",
    "Island Uni Morphing Potion",
    "Faerie Ruki Morphing Potion",
    "Green Krawk Morphing Potion",
    "Fire Lupe Morphing Potion",
    "Plushie Chomby Morphing Potion",
    "Fire Blumaroo Morphing Potion",
    "Blue Gelert Morphing Potion",
    "Shadow Blumaroo Morphing Potion",
    "Baby Bruce Morphing Potion",
    "Cloud Gelert Morphing Potion",
    "Red Gelert Morphing Potion",
    "Plushie Grarrl Morphing Potion",
    "Faerie JubJub Morphing Potion",
    "Pink Draik Morphing Potion",
    "Fire Xweetok Morphing Potion",
    "Baby Koi Morphing Potion",
    "Red Kacheek Morphing Potion",
    "Yellow Jetsam Morphing Potion",
    "Pirate Kacheek Morphing Potion",
    "Desert Hissi Morphing Potion",
    "Baby Uni Morphing Potion",
    "Baby Blumaroo Morphing Potion",
    "Ghost Draik Morphing Potion",
    "Halloween Korbat Morphing Potion",
    "Shadow Ruki Morphing Potion",
    "Christmas Gelert Morphing Potion",
    "Island Blumaroo Morphing Potion",
    "Baby Gnorbu Morphing Potion",
    "Darigan Bori Morphing Potion",
    "Blue Cybunny Morphing Potion",
    "Baby Kougra Morphing Potion",
    "Electric Ixi Morphing Potion",
    "Faerie Acara Morphing Potion",
    "Eventide Gelert Morphing Potion",
    "Island Zafara Morphing Potion",
    "Baby Acara Morphing Potion",
    "Maraquan Korbat Morphing Potion",
    "Plushie Scorchio Morphing Potion",
    "Ghost Gelert Morphing Potion",
    "Baby JubJub Morphing Potion",
    "Island Krawk Morphing Potion",
    "Baby Buzz Morphing Potion",
    "Shadow Peophin Morphing Potion",
    "Invisible Wocky Morphing Potion",
    "Desert Flotsam Morphing Potion",
    "Cloud Cybunny Morphing Potion",
    "White Ixi Morphing Potion",
    "Wraith Shoyru Morphing Potion",
    "Grey Zafara Morphing Potion",
    "Transparent Wocky Morphing Potion",
    "Rainbow Chomby Morphing Potion",
    "Water Usul Morphing Potion",
    "Christmas Kacheek Morphing Potion",
    "Purple Draik Morphing Potion",
    "Grey Techo Morphing Potion",
    "Baby Usul Morphing Potion",
    "Pirate Cybunny Morphing Potion",
    "Yellow Zafara Morphing Potion",
    "Ghost Hissi Morphing Potion",
    "Eventide Aisha Morphing Potion",
    "Baby Kiko Morphing Potion",
    "White Xweetok Morphing Potion",
    "Pink Ruki Morphing Potion",
    "Grey Grarrl Morphing Potion",
    "Fire Chomby Morphing Potion",
    "Eventide Poogle Morphing Potion",
    "Light Faerie Dust",
    "Halloween Nimmo Morphing Potion",
    "Plushie Tuskaninny Morphing Potion",
    "Strawberry Kacheek Morphing Potion",
    "Fire Kacheek Morphing Potion",
    "Green Kacheek Morphing Potion",
    "Darigan Grarrl Morphing Potion",
    "Desert Chomby Morphing Potion",
    "Desert Elephante Morphing Potion",
    "Maraquan Mynci Morphing Potion",
    "Baby Shoyru Morphing Potion",
    "Maractite Aisha Morphing Potion",
    "Island Poogle Morphing Potion",
    "Blue Lupe Morphing Potion",
    "Green Draik Morphing Potion",
    "Green Lupe Morphing Potion",
    "Christmas Cybunny Morphing Potion",
    "Rainbow Cybunny Morphing Potion",
    "Plushie Ixi Morphing Potion",
    "Eventide Hissi Morphing Potion",
    "Yellow Cybunny Morphing Potion",
    "Halloween Eyrie Morphing Potion",
    "Island Xweetok Morphing Potion",
    "Darigan Kau Morphing Potion",
    "Faerie Pteri Morphing Potion",
    "Zombie Cybunny Morphing Potion",
    "Plushie Kau Morphing Potion",
    "Transparent Skeith Morphing Potion",
    "Rainbow Kacheek Morphing Potion",
    "Red Zafara Morphing Potion",
    "Plushie Grundo Morphing Potion",
    "Baby Poogle Morphing Potion",
    "Red Krawk Morphing Potion",
    "Yellow Krawk Morphing Potion",
    "Skunk Draik Morphing Potion",
    "Baby Grundo Morphing Potion",
    "Fire Shoyru Morphing Potion",
    "Apple Chia Morphing Potion",
    "Dimensional Aisha Morphing Potion",
    "Camouflage Cybunny Morphing Potion",
    "White Chomby Morphing Potion",
    "Disco Shoyru Morphing Potion",
    "Striped Xweetok Morphing Potion",
    "Green Cybunny Morphing Potion",
    "Starry Draik Morphing Potion",
    "Plushie Kougra Morphing Potion",
    "Camouflage Krawk Morphing Potion",
    "Plushie Flotsam Morphing Potion",
    "Spotted Jetsam Morphing Potion",
    "Shadow Chomby Morphing Potion",
    "Faerie Nimmo Morphing Potion",
    "Blue Zafara Morphing Potion",
    "Spotted Koi Morphing Potion",
    "Faerie Meerca Morphing Potion",
    "Darigan Kyrii Morphing Potion",
    "Plushie Yurble Morphing Potion",
    "Split Lupe Morphing Potion",
    "Wraith Ogrin Morphing Potion",
    "Brown Ixi Morphing Potion",
    "Green Jetsam Morphing Potion",
    "Stealthy Techo Morphing Potion",
    "Darigan Acara Morphing Potion",
    "Faerie Yurble Morphing Potion",
    "Maraquan Hissi Morphing Potion",
    "Clay Aisha Morphing Potion",
    "Polkadot Tonu Morphing Potion",
    "Shadow Hissi Morphing Potion",
    "Strawberry Lupe Morphing Potion",
    "Pirate Poogle Morphing Potion",
    "Desert Poogle Morphing Potion",
    "Island Grundo Morphing Potion",
    "Faerie Kau Morphing Potion",
    "Halloween Xweetok Morphing Potion",
    "Starry Zafara Morphing Potion",
    "Pirate Kougra Morphing Potion",
    "Plushie Wocky Morphing Potion",
    "Water Gnorbu Morphing Potion",
    "Plushie Jetsam Morphing Potion",
    "Christmas Ixi Morphing Potion",
    "Darigan Grundo Morphing Potion",
    "Grey Yurble Morphing Potion",
    "Christmas Lupe Morphing Potion",
    "Faerie Aisha Morphing Potion",
    "Skunk Lupe Morphing Potion",
    "Baby Peophin Morphing Potion",
    "Faerie Uni Morphing Potion",
    "Eventide Zafara Morphing Potion",
    "Darigan Techo Morphing Potion",
    "Halloween Techo Morphing Potion",
    "Glowing Jetsam Morphing Potion",
    "Plushie Buzz Morphing Potion",
    "Snow Usul Morphing Potion",
    "Shadow Uni Morphing Potion",
    "Desert Peophin Morphing Potion",
    "Pirate Wocky Morphing Potion",
    "Island Aisha Morphing Potion",
    "Dimensional Jetsam Morphing Potion",
    "Transparent Lenny Morphing Potion",
    "Purple Zafara Morphing Potion",
    "Swamp Gas Techo Morphing Potion",
    "Yellow Ixi Morphing Potion",
    "Blue Peophin Morphing Potion",
    "Fire Pteri Morphing Potion",
    "Green Ixi Morphing Potion",
    "Disco Chomby Morphing Potion",
    "Plushie Techo Morphing Potion",
    "Yellow Grundo Morphing Potion",
    "Green Zafara Morphing Potion",
    "Purple Eyrie Morphing Potion",
    "Red Peophin Morphing Potion",
    "Camouflage Chia Morphing Potion",
    "Starry Usul Morphing Potion",
    "Blue Jetsam Morphing Potion",
    "Blue Kiko Morphing Potion",
    "Shadow Lenny Morphing Potion",
    "Dimensional Kougra Morphing Potion",
    "Green Ruki Morphing Potion",
    "Red Usul Morphing Potion",
    "Yellow Skeith Morphing Potion",
    "Pirate Lenny Morphing Potion",
    "Yellow Peophin Morphing Potion",
    "Island Usul Morphing Potion",
    "Purple Peophin Morphing Potion",
    "Red Ixi Morphing Potion",
    "White Flotsam Morphing Potion",
    "Rainbow Gnorbu Morphing Potion",
    "Green Chia Morphing Potion",
    "Electric Grarrl Morphing Potion",
    "Cloud Lenny Morphing Potion",
    "Red Shoyru Morphing Potion",
    "Christmas Kougra Morphing Potion",
    "Blue Ixi Morphing Potion",
    "Cloud Ixi Morphing Potion",
    "Grey Mynci Morphing Potion",
    "Brown Grundo Morphing Potion",
    "Checkered Acara Morphing Potion",
    "Blue Lenny Morphing Potion",
    "Red Kiko Morphing Potion",
    "Silver Peophin Morphing Potion",
    "Yellow Chia Morphing Potion",
    "Desert Kyrii Morphing Potion",
    "Yellow Kiko Morphing Potion",
    "Darigan Mynci Morphing Potion",
    "Snow Chia Morphing Potion",
    "Blue Korbat Morphing Potion",
    "Red Korbat Morphing Potion",
    "Green Shoyru Morphing Potion",
    "Pink Eyrie Morphing Potion",
    "Blue Acara Morphing Potion",
    "Island Kiko Morphing Potion",
    "Rainbow JubJub Morphing Potion",
    "Glowing Lupe Morphing Potion",
    "Christmas Grundo Morphing Potion",
    "Purple Shoyru Morphing Potion",
    "Yellow Chomby Morphing Potion",
    "Yellow Acara Morphing Potion",
    "Spotted Shoyru Morphing Potion",
    "Yellow Kau Morphing Potion",
    "Fire Chia Morphing Potion",
    "Purple Poogle Morphing Potion",
    "Blue Chia Morphing Potion",
    "Island Eyrie Morphing Potion",
    "Snow Eyrie Morphing Potion",
    "Red Chia Morphing Potion",
    "Green Hissi Morphing Potion",
    "Red Acara Morphing Potion",
    "Christmas Pteri Morphing Potion",
    "Snow Blumaroo Morphing Potion",
    "Ghost Shoyru Morphing Potion",
    "Green Kiko Morphing Potion",
    "Christmas Bruce Morphing Potion",
    "Fire Acara Morphing Potion",
    "Brown Bruce Morphing Potion",
    "Brown Ruki Morphing Potion",
    "Disco Acara Morphing Potion",
    "Cloud Acara Morphing Potion",
    "Eventide Ixi Morphing Potion",
    "Yellow Bruce Morphing Potion",
    "Maraquan Buzz Morphing Potion",
    "Green Peophin Morphing Potion",
    "Island Acara Morphing Potion",
    "Yellow Lenny Morphing Potion",
    "Island Korbat Morphing Potion",
    "Yellow Korbat Morphing Potion",
    "Yellow Hissi Morphing Potion",
    "Pink Uni Morphing Potion",
    "Striped Shoyru Morphing Potion",
    "Yellow Wocky Morphing Potion",
    "Cloud Grarrl Morphing Potion",
    "Ghost Acara Morphing Potion",
    "Fire Wocky Morphing Potion",
    "Starry Hissi Morphing Potion",
    "Blue Grundo Morphing Potion",
    "Green Acara Morphing Potion",
    "Yellow Ruki Morphing Potion",
    "Rainbow Koi Morphing Potion",
    "Red Kau Morphing Potion",
    "Pink Korbat Morphing Potion",
    "Purple Grundo Morphing Potion",
    "Green Grundo Morphing Potion",
    "Pink Kyrii Morphing Potion",
    "Blue Shoyru Morphing Potion",
    "Blue Usul Morphing Potion",
    "Christmas Blumaroo Morphing Potion",
    "Fire Kiko Morphing Potion",
    "Christmas Koi Morphing Potion",
    "Cloud Eyrie Morphing Potion",
    "Faerie Buzz Morphing Potion",
    "Snow Bruce Morphing Potion",
    "Checkered Kiko Morphing Potion",
    "Dimensional Shoyru Morphing Potion",
    "Striped Tuskaninny Morphing Potion",
    "Island Ogrin Morphing Potion",
    "Fire Ruki Morphing Potion",
    "Red Chomby Morphing Potion",
    "Blue Chomby Morphing Potion",
    "Red Lupe Morphing Potion",
    "Blue Wocky Morphing Potion",
    "Pink Shoyru Morphing Potion",
    "Striped Kau Morphing Potion",
    "Island Shoyru Morphing Potion",
    "Rainbow Flotsam Morphing Potion",
    "Water Faerie Bubbles",
    "Starry Skeith Morphing Potion",
    "Faerie Tuskaninny Morphing Potion",
    "Green Chomby Morphing Potion",
    "Fire Ixi Morphing Potion",
    "Silver Shoyru Morphing Potion",
    "Fire Yurble Morphing Potion",
    "Brown Aisha Morphing Potion",
    "Blue Quiggle Morphing Potion",
    "Rainbow Grundo Morphing Potion",
    "Yellow Aisha Morphing Potion",
    "Green Kau Morphing Potion",
    "Spotted Grundo Morphing Potion",
    "Shadow Shoyru Morphing Potion",
    "Green Korbat Morphing Potion",
    "Starry Eyrie Morphing Potion",
    "Water Buzz Morphing Potion",
    "Spotted Pteri Morphing Potion",
    "Woodland Acara Morphing Potion",
    "Fire Quiggle Morphing Potion",
    "Dimensional Poogle Morphing Potion",
    "Island Wocky Morphing Potion",
    "Snow Bori Morphing Potion",
    "Purple Pteri Morphing Potion",
    "Christmas Magic Hat",
    "Blue Bori Morphing Potion",
    "Rainbow Wocky Morphing Potion",
    "Island Koi Morphing Potion",
    "Christmas Wocky Morphing Potion",
    "Green Usul Morphing Potion",
    "Christmas Shoyru Morphing Potion",
    "Pirate Ixi Morphing Potion",
    "Fire Bori Morphing Potion",
    "Swamp Gas Ogrin Morphing Potion",
    "Skunk Eyrie Morphing Potion",
    "Blue Tonu Morphing Potion",
    "Cloud Ruki Morphing Potion",
    "Red Hissi Morphing Potion",
    "Zombie Usul Morphing Potion",
    "Glowing Korbat Morphing Potion",
    "Starry Bruce Morphing Potion",
    "Red Skeith Morphing Potion",
    "Cloud Shoyru Morphing Potion",
    "Blue Skeith Morphing Potion",
    "Red Ruki Morphing Potion",
    "Red Elephante Morphing Potion",
    "Blue Hissi Morphing Potion",
    "Green Wocky Morphing Potion",
    "Ghost Lenny Morphing Potion",
    "Blue Koi Morphing Potion",
    "Purple Uni Morphing Potion",
    "Halloween Kau Morphing Potion",
    "Rainbow Kau Morphing Potion",
    "Skunk Flotsam Morphing Potion",
    "Fire Kau Morphing Potion",
    "Starry Shoyru Morphing Potion",
    "Starry Kau Morphing Potion",
    "Tyrannian JubJub Morphing Potion",
    "Fire Skeith Morphing Potion",
    "Striped Meerca Morphing Potion",
    "Cloud Grundo Morphing Potion",
    "White Peophin Morphing Potion",
    "Green Lenny Morphing Potion",
    "Yellow Usul Morphing Potion",
    "Blue Kau Morphing Potion",
    "Pirate Chomby Morphing Potion",
    "Blue Aisha Morphing Potion",
    "Woodland Grundo Morphing Potion",
    "Sketch Peophin Morphing Potion",
    "Tyrannian Eyrie Morphing Potion",
    "Rainbow Kyrii Morphing Potion",
    "Eventide Kougra Morphing Potion",
    "Yellow Shoyru Morphing Potion",
    "Snow Wocky Morphing Potion",
    "Woodland Mynci Morphing Potion",
    "Blue Ruki Morphing Potion",
    "Christmas Peophin Morphing Potion",
    "Red Bori Morphing Potion",
    "Plushie Pteri Morphing Potion",
    "Zombie Aisha Morphing Potion",
    "Snow Aisha Morphing Potion",
    "Tyrannian Gnorbu Morphing Potion",
    "Split Bruce Morphing Potion",
    "Gold Shoyru Morphing Potion",
    "Rainbow Aisha Morphing Potion",
    "Split Chia Morphing Potion",
    "Starry Grundo Morphing Potion",
    "Disco Bruce Morphing Potion",
    "Cloud Bori Morphing Potion",
    "Shadow Skeith Morphing Potion",
    "Yellow Bori Morphing Potion",
    "Cloud Scorchio Morphing Potion",
    "Spotted Korbat Morphing Potion",
    "Pastel Gnorbu Morphing Potion",
    "Checkered Bori Morphing Potion",
    "Pink Peophin Morphing Potion",
    "Red Eyrie Morphing Potion",
    "Yellow Blumaroo Morphing Potion",
    "Ghost Korbat Morphing Potion",
    "Christmas Chomby Morphing Potion",
    "Blue Kougra Morphing Potion",
    "Rainbow Uni Morphing Potion",
    "Relic Chia Morphing Potion",
    "Ghost Kiko Morphing Potion",
    "Striped Skeith Morphing Potion",
    "Christmas Zafara Morphing Potion",
    "Cloud Wocky Morphing Potion",
    "Island Buzz Morphing Potion",
    "Red Wocky Morphing Potion",
    "Checkered Shoyru Morphing Potion",
    "Tyrannian Flotsam Morphing Potion",
    "Red Bruce Morphing Potion",
    "Tyrannian Usul Morphing Potion",
    "Fire Bruce Morphing Potion",
    "White Chia Morphing Potion",
    "Striped Chia Morphing Potion",
    "Purple Chia Morphing Potion",
    "Green Bruce Morphing Potion",
    "Rainbow Shoyru Morphing Potion",
    "Cloud Bruce Morphing Potion",
    "Starry Bori Morphing Potion",
    "Desert Grundo Morphing Potion",
    "Island Chomby Morphing Potion",
    "White Kyrii Morphing Potion",
    "Shadow Korbat Morphing Potion",
    "Disco Korbat Morphing Potion",
    "Striped Ixi Morphing Potion",
    "Island Skeith Morphing Potion",
    "Green Blumaroo Morphing Potion",
    "Christmas Acara Morphing Potion",
    "Fire Techo Morphing Potion",
    "Rainbow Grarrl Morphing Potion",
    "Red Blumaroo Morphing Potion",
    "Rainbow Korbat Morphing Potion",
    "Cloud Peophin Morphing Potion",
    "Green Skeith Morphing Potion",
    "Christmas Chia Morphing Potion",
    "White Shoyru Morphing Potion",
    "Rainbow Poogle Morphing Potion",
    "Skunk Kyrii Morphing Potion",
    "Brown Uni Morphing Potion",
    "Ghost Peophin Morphing Potion",
    "Green Tuskaninny Morphing Potion",
    "Speckled Bruce Morphing Potion",
    "Christmas Bori Morphing Potion",
    "Checkered Poogle Morphing Potion",
    "Checkered Aisha Morphing Potion",
    "Water Acara Morphing Potion",
    "Christmas Korbat Morphing Potion",
    "Blue Blumaroo Morphing Potion",
    "Speckled Shoyru Morphing Potion",
    "Green Poogle Morphing Potion",
    "Starry Korbat Morphing Potion",
    "Green Bori Morphing Potion",
    "Flaming Torch",
    "Pink Pteri Morphing Potion",
    "Starry Ruki Morphing Potion",
    "Christmas Uni Morphing Potion",
    "Island Nimmo Morphing Potion",
    "Speckled Kau Morphing Potion",
    "Yellow Elephante Morphing Potion",
    "Red Aisha Morphing Potion",
    "Christmas Kiko Morphing Potion",
    "Starry Scorchio Morphing Potion",
    "Speckled Xweetok Morphing Potion",
    "Green JubJub Morphing Potion",
    "Red Grarrl Morphing Potion",
    "Desert Tuskaninny Morphing Potion",
    "Pirate Grundo Morphing Potion",
    "Christmas JubJub Morphing Potion",
    "Snow Ogrin Morphing Potion",
    "Woodland Lenny Morphing Potion",
    "Pink Koi Morphing Potion",
    "White Skeith Morphing Potion",
    "Green Pteri Morphing Potion",
    "Starry Pteri Morphing Potion",
    "Blue Uni Morphing Potion",
    "Yellow Nimmo Morphing Potion",
    "Pirate Gnorbu Morphing Potion",
    "Fire Moehog Morphing Potion",
    "Red Lenny Morphing Potion",
    "Pink Ogrin Morphing Potion",
    "Purple Aisha Morphing Potion",
    "Red Kougra Morphing Potion",
    "Island Techo Morphing Potion",
    "Faerie Mynci Morphing Potion",
    "Desert Chia Morphing Potion",
    "Electric Moehog Morphing Potion",
    "Rainbow Bori Morphing Potion",
    "Yellow Poogle Morphing Potion",
    "Camouflage JubJub Morphing Potion",
    "Fire Aisha Morphing Potion",
    "Striped Scorchio Morphing Potion",
    "Grey Lenny Morphing Potion",
    "Ghost Techo Morphing Potion",
    "Red Mynci Morphing Potion",
    "Christmas Scorchio Morphing Potion",
    "Faerie Skeith Morphing Potion",
    "Desert Scorchio Morphing Potion",
    "Woodland Peophin Morphing Potion",
    "Water Kyrii Morphing Potion",
    "Cloud Poogle Morphing Potion",
    "Starry Uni Morphing Potion",
    "Rainbow Tuskaninny Morphing Potion",
    "Starry Yurble Morphing Potion",
    "Strawberry Tuskaninny Morphing Potion",
    "Purple Tonu Morphing Potion",
    "Starry Xweetok Morphing Potion",
    "Green Quiggle Morphing Potion",
    "Pirate Usul Morphing Potion",
    "Zombie Korbat Morphing Potion",
    "Strawberry Techo Morphing Potion",
    "Green Koi Morphing Potion",
    "Striped Blumaroo Morphing Potion",
    "Red Koi Morphing Potion",
    "Island Tuskaninny Morphing Potion",
    "Pirate Hissi Morphing Potion",
    "Strawberry Bruce Morphing Potion",
    "Pirate Flotsam Morphing Potion",
    "Ghost Grarrl Morphing Potion",
    "Red Pteri Morphing Potion",
    "Yellow Moehog Morphing Potion",
    "Spotted Nimmo Morphing Potion",
    "Camouflage Shoyru Morphing Potion",
    "Speckled Bori Morphing Potion",
    "Desert Ogrin Morphing Potion",
    "Fire Kyrii Morphing Potion",
    "Blue Bruce Morphing Potion",
    "Red Nimmo Morphing Potion",
    "Striped Korbat Morphing Potion",
    "Christmas Lenny Morphing Potion",
    "Disco Mynci Morphing Potion",
    "Striped Grarrl Morphing Potion",
    "Water Flotsam Morphing Potion",
    "Blue Eyrie Morphing Potion",
    "Purple Yurble Morphing Potion",
    "Red Scorchio Morphing Potion",
    "Blue Poogle Morphing Potion",
    "Christmas Aisha Morphing Potion",
    "Gold Tonu Morphing Potion",
    "Green Aisha Morphing Potion",
    "Orange Tuskaninny Morphing Potion",
    "Woodland Pteri Morphing Potion",
    "Green Meerca Morphing Potion",
    "Green Nimmo Morphing Potion",
    "Blue Tuskaninny Morphing Potion",
    "Shadow Ogrin Morphing Potion",
    "Tyrannian Peophin Morphing Potion",
    "Brown Lenny Morphing Potion",
    "Starry Nimmo Morphing Potion",
    "Cloud Elephante Morphing Potion",
    "Desert Buzz Morphing Potion",
    "Eventide Korbat Morphing Potion",
    "Red Yurble Morphing Potion",
    "Green Moehog Morphing Potion",
    "Yellow Kougra Morphing Potion",
    "Yellow JubJub Morphing Potion",
    "Spotted Blumaroo Morphing Potion",
    "Zombie Buzz Morphing Potion",
    "Water Kau Morphing Potion",
    "Skunk Mynci Morphing Potion",
    "Red JubJub Morphing Potion",
    "Blue Pteri Morphing Potion",
    "Yellow Pteri Morphing Potion",
    "Gold Scorchio Morphing Potion",
    "Glowing Poogle Morphing Potion",
    "Yellow Tonu Morphing Potion",
    "Green Flotsam Morphing Potion",
    "Green Tonu Morphing Potion",
    "Starry Koi Morphing Potion",
    "Rainbow Ogrin Morphing Potion",
    "Red Kyrii Morphing Potion",
    "Yellow Quiggle Morphing Potion",
    "Striped Aisha Morphing Potion",
    "Ghost Tuskaninny Morphing Potion",
    "Snow Techo Morphing Potion",
    "Green Buzz Morphing Potion",
    "Christmas Gnorbu Morphing Potion",
    "Fire Buzz Morphing Potion",
    "Striped Flotsam Morphing Potion",
    "Fire Gnorbu Morphing Potion",
    "Blue Yurble Morphing Potion",
    "Yellow Mynci Morphing Potion",
    "Dimensional Moehog Morphing Potion",
    "Disco Moehog Morphing Potion",
    "Red Flotsam Morphing Potion",
    "Starry Wocky Morphing Potion",
    "Cloud Pteri Morphing Potion",
    "Brown Kougra Morphing Potion",
    "Tyrannian Ixi Morphing Potion",
    "Wraith Bruce Morphing Potion",
    "Green Grarrl Morphing Potion",
    "Skunk Buzz Morphing Potion",
    "Yellow Koi Morphing Potion",
    "Green Yurble Morphing Potion",
    "Tyrannian Nimmo Morphing Potion",
    "Woodland Koi Morphing Potion",
    "Yellow Yurble Morphing Potion",
    "Striped Nimmo Morphing Potion",
    "Orange Yurble Morphing Potion",
    "Brown Techo Morphing Potion",
    "Spotted Flotsam Morphing Potion",
    "Blue Mynci Morphing Potion",
    "Red Tuskaninny Morphing Potion",
    "Camouflage Kyrii Morphing Potion",
    "Green Kougra Morphing Potion",
    "Starry Tuskaninny Morphing Potion",
    "Faerie Flotsam Morphing Potion",
    "Faerie Eyrie Morphing Potion",
    "Tyrannian Bori Morphing Potion",
    "Red Quiggle Morphing Potion",
    "Camouflage Lenny Morphing Potion",
    "Blue JubJub Morphing Potion",
    "Green Techo Morphing Potion",
    "Snowbunny Stamp",
    "Battle Slices Stamp",
    "Shenkuu Stamp",
    "Sticky Snowflake Stamp",
    "Queen Fyora Stamp",
    "King Kelpbeard Stamp",
    "Captain Scarblade Stamp",
    "King Altador Stamp",
    "Igneot Stamp",
    "ARGH!!!! DONNA STAMP",
    "Holographic Coltzans Shrine Stamp",
    "Scuzzy Stamp",
    "Sasha Stamp",
    "Terask Stamp",
    "Lord Kass Stamp",
    "Lab Ray Stamp",
    "Misprint Meuka Stamp",
    "Double Printed Evil Fuzzle Stamp",
    "Darigan Spectre Stamp",
    "King Jazan Stamp",
    "Holographic Virtupets Stamp",
    "Misaligned Printer Stamp",
    "Inverted Space Faerie Stamp",
    "The Three Stamp",
    "Dark Battle Duck Stamp",
    "Holographic Magax Stamp",
    "Foil Food Shop Stamp",
    "Upside Down Island Acara Stamp",
    "Jhudoras Cloud Stamp",
    "Foil Slorg Stamp",
    "Nibbled Cooking Pot Stamp",
    "Xantan Stamp",
    "The Great Battle Stamp",
    "Need a Better Printer Stamp",
    "Quilin Stamp",
    "One Hundred Million Neopoint Stamp",
    "Grimtooth Stamp",
    "Darkest Faerie Stamp",
    "Jacques Stamp",
    "Skeith Defender Stamp",
    "Garin Stamp",
    "Hadrak Stamp",
    "Stone Stamp",
    "Isca Stamp",
    "Meerca Spy Stamp",
    "Wise Gnorbu Stamp",
    "Rainbow Sticky Hand Stamp",
    "Morguss Stamp",
    "Virtupets Space Station Stamp",
    "Ramtor Stamp",
    "Geraptiku Stamp",
    "Usuki Doll Stamp",
    "Nightsteed Stamp",
    "NeoQuest II Esophagor Stamp",
    "NeoQuest Hero Stamp",
    "Sword Of Apocalypse Stamp",
    "Jahbal Stamp",
    "NeoQuest Logo Stamp",
    "Grundo Warehouse Stamp",
    "Court Dancer Stamp",
    "Igneots Cavern Stamp",
    "Count Von Roo Plushie Stamp",
    "Drackonack Stamp",
    "Ready to Roll Stamp",
    "Aethia Stamp",
    "Count Von Roo Stamp",
    "Shiny Monoceraptor Stamp",
    "Darigan Moehog Stamp",
    "Nabile Stamp",
    "Von Roos Castle Stamp",
    "Gors The Mighty Stamp",
    "Battle Uni Stamp",
    "Anshu Fishing Stamp",
    "Blugthak Stamp",
    "Guardian Of Spectral Magic Stamp",
    "Golden Dubloon Stamp",
    "Torakor Stamp",
    "Morris Stamp",
    "The Cyodrakes Gaze Stamp",
    "Anubits Stamp",
    "Gold Mote Stamp",
    "Northern Watch Tower Stamp",
    "Cybunny on a Cycle Stamp",
    "Capn Threelegs Stamp",
    "Lucky Coin Stamp",
    "The Sleeper Constellation Stamp",
    "Biyako Stamp",
    "Altador Travel Stamp",
    "Lampwyck Stamp",
    "Zafara Double Agent Stamp",
    "Lost City of Phorofor Stamp",
    "Fyoras Castle Stamp",
    "Tomos Stamp",
    "Forgotten Shore Stamp",
    "Shadow Gulch Stamp",
    "Mystery Island Aishas Stamp",
    "Swordsmaster Talek Stamp",
    "Mipsy Stamp",
    "Tyrannian Victory Day Stamp",
    "Meridell Heroes Stamp",
    "Darigan Citadel Stamp",
    "Yellow Knight Stamp",
    "Shenkuu Helmet Stamp",
    "Altador Magic Stamp",
    "Rainbow Pteri Feather Stamp",
    "Commemorative Defenders Stamp #4",
    "Talinia Stamp",
    "Faerie Slorg Stamp",
    "Luperus Right Head Stamp",
    "Luperus Centre Head Stamp",
    "Scordrax Stamp",
    "Gargarox Isafuhlarg Stamp",
    "Dark Faerie Stamp",
    "Haunted Mansion Stamp",
    "Shumi Telescope Stamp",
    "Dark Qasala Stamp",
    "Space Faerie Stamp",
    "Singed Tyrannian Volcano Stamp",
    "Dark Ilere Stamp",
    "The Academy Stamp",
    "Zombified Heroes Stamp",
    "Meridell Castle Stamp",
    "Mr. Krawley Stamp",
    "Wheel of Monotony Stamp",
    "Dr. Sloth Stamp",
    "Hot Dog Hero Stamp",
    "Blumaroo Court Jester Stamp",
    "Moltara Town Hall Stamp",
    "The Krawken Stamp",
    "Luperus Left Head Stamp",
    "Destruction of Faerieland Stamp",
    "Orrin Stamp",
    "Shenkuu Mask Stamp",
    "Zurroball Stamp",
    "Thoughtful Linae Stamp",
];